"""
Extraction de features image avec LLaVA-1.5-7B (4-bit).

Pour chaque image on demande a LLaVA un JSON structure :
  - llava_score_real      : proba que l'image soit une vraie photo
  - llava_score_artifact  : presence d'artefacts visuels typiques d'IA
  - llava_score_coherence : coherence interne (textures, ombres, perspectives)
  - llava_observation     : description courte des elements suspects/rassurants

Avec sauvegarde incrementale + resume automatique.

Usage :
    python 03_src/features/extract_llava.py --limit-to-domain --save-every 20
    # Si interrompu, relancer la meme commande pour reprendre.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import re
from pathlib import Path

import pandas as pd
import torch
from PIL import Image
from tqdm import tqdm
from transformers import (
    AutoProcessor,
    BitsAndBytesConfig,
    LlavaForConditionalGeneration,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

MODEL_ID = "llava-hf/llava-1.5-7b-hf"

ANALYSIS_PROMPT = """USER: <image>
You are a forensic image analyst evaluating whether this picture is an AUTHENTIC photograph
or an image GENERATED BY AN AI MODEL (such as Stable Diffusion, Midjourney, DALL-E).

Look carefully for:
- Inconsistent textures, blurry boundaries between objects
- Impossible lighting / reflections / shadows
- Misaligned details (text, hands, repeated patterns)
- Over-smooth surfaces, unnatural colors

Reply ONLY with a JSON object (no commentary), with this exact schema:
{
  "score_real": float between 0 and 1 (probability the image is a real photograph),
  "score_artifact": float between 0 and 1 (presence of AI-generation artifacts),
  "score_coherence": float between 0 and 1 (internal scene coherence: shadows, perspective, textures),
  "observation": short string (max 200 chars), the most salient suspicious or reassuring detail
}
ASSISTANT:"""

NEW_COLS = ["llava_score_real", "llava_score_artifact", "llava_score_coherence", "llava_observation"]


def load_llava(device: str = None):
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"
    logger.info("Chargement LLaVA-1.5-7B (device=%s)...", device)
    processor = AutoProcessor.from_pretrained(MODEL_ID)
    if device == "cuda":
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_quant_type="nf4",
        )
        model = LlavaForConditionalGeneration.from_pretrained(
            MODEL_ID, quantization_config=bnb_config, device_map="auto"
        )
    else:
        model = LlavaForConditionalGeneration.from_pretrained(
            MODEL_ID, torch_dtype=torch.float32
        ).to(device)
    model.eval()
    return model, processor, device


@torch.no_grad()
def analyse_one(model, processor, image: Image.Image) -> dict:
    inputs = processor(text=ANALYSIS_PROMPT, images=image, return_tensors="pt").to(
        model.device, torch.float16 if model.device.type == "cuda" else torch.float32
    )
    outputs = model.generate(
        **inputs, max_new_tokens=200, do_sample=False, pad_token_id=processor.tokenizer.eos_token_id
    )
    text = processor.decode(outputs[0], skip_special_tokens=True)
    answer = text.split("ASSISTANT:")[-1].strip()
    return parse_json_answer(answer)


def parse_json_answer(text: str) -> dict:
    default = {c: None for c in NEW_COLS}
    if not text:
        return default
    match = re.search(r"\{[\s\S]*?\}", text)
    if not match:
        return default
    try:
        parsed = json.loads(match.group(0))
        return {
            "llava_score_real": _to_float(parsed.get("score_real")),
            "llava_score_artifact": _to_float(parsed.get("score_artifact")),
            "llava_score_coherence": _to_float(parsed.get("score_coherence")),
            "llava_observation": _to_str(parsed.get("observation")),
        }
    except (json.JSONDecodeError, TypeError):
        return default


def _to_float(v):
    if v is None:
        return None
    try:
        return max(0.0, min(1.0, float(v)))
    except (TypeError, ValueError):
        return None


def _to_str(v):
    if v is None:
        return None
    s = str(v).strip()
    return s[:300] if s else None


def atomic_save(df: pd.DataFrame, out_path: Path):
    tmp = out_path.with_suffix(".parquet.tmp")
    df.to_parquet(tmp, index=False)
    os.replace(tmp, out_path)


def init_or_resume(df: pd.DataFrame, out_path: Path) -> pd.DataFrame:
    if out_path.exists():
        try:
            partial = pd.read_parquet(out_path)
            if len(partial) == len(df) and set(partial["image_path"]) == set(df["image_path"]):
                partial = partial.set_index("image_path").loc[df["image_path"]].reset_index()
                logger.info("Partiel valide trouve : resume actif")
                return partial
            logger.warning("Partiel incompatible, on recommence")
        except Exception as e:
            logger.warning("Lecture partielle echouee : %s", e)
    out = df.copy().reset_index(drop=True)
    for c in NEW_COLS:
        out[c] = None
    return out


def extract_with_resume(df: pd.DataFrame, root: Path, out_path: Path, save_every: int = 20) -> pd.DataFrame:
    df_work = init_or_resume(df, out_path).reset_index(drop=True)
    n = len(df_work)
    done_count = int(df_work["llava_score_real"].notna().sum())
    logger.info("Deja fait : %d / %d", done_count, n)

    model, processor, _ = load_llava()

    saved_since = 0
    pbar = tqdm(total=n, initial=done_count, desc="LLaVA")
    for idx in range(n):
        if pd.notna(df_work.at[idx, "llava_score_real"]):
            continue
        path = root / df_work.at[idx, "image_path"]
        try:
            img = Image.open(path).convert("RGB")
            res = analyse_one(model, processor, img)
        except Exception as e:
            logger.warning("Echec %s : %s", path, e)
            res = {c: None for c in NEW_COLS}

        # Si tout est None on met une sentinelle pour ne pas reboucler dessus eternellement
        if all(v is None for v in res.values()):
            res["llava_score_real"] = 0.5
            res["llava_score_artifact"] = 0.5
            res["llava_score_coherence"] = 0.5
            res["llava_observation"] = ""

        for c in NEW_COLS:
            df_work.at[idx, c] = res.get(c)

        pbar.update(1)
        saved_since += 1
        if saved_since >= save_every:
            atomic_save(df_work, out_path)
            saved_since = 0
    pbar.close()
    atomic_save(df_work, out_path)
    return df_work


def main():
    parser = argparse.ArgumentParser(description="Features LLaVA (avec resume)")
    parser.add_argument("--dataset", type=Path,
                        default=Path("01_data/processed/dataset_with_blip2.parquet"))
    parser.add_argument("--out", type=Path,
                        default=Path("01_data/processed/dataset_with_lmm.parquet"))
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--save-every", type=int, default=20,
                        help="Sauvegarde tous les N images traitees (defaut 20)")
    parser.add_argument("--limit-to-domain", action="store_true",
                        help="Ne calcule que sur les splits domain_* (recommande sur Colab Free)")
    args = parser.parse_args()

    df = pd.read_parquet(args.dataset)
    if args.limit_to_domain:
        df = df[df["split"].astype(str).str.startswith("domain_")].reset_index(drop=True)
        logger.info("Limite au domaine habitation : %d lignes", len(df))
    else:
        logger.info("Dataset complet : %d lignes", len(df))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    extract_with_resume(df, args.root, args.out, save_every=args.save_every)
    logger.info("Sauvegarde finale : %s", args.out)


if __name__ == "__main__":
    main()
