"""
Extraction de features image avec BLIP-2.

Pour chaque image on calcule :
  - blip2_caption    : caption libre genere par BLIP-2
  - blip2_score_real : reponse VQA "Is this a real photograph?" -> proba "yes"
  - blip2_score_ai   : reponse VQA "Is this AI generated?" -> proba "yes"
  - blip2_score_artifact : reponse VQA "Are there any visual artifacts in this image?" -> proba "yes"

BLIP-2 OPT-2.7B : ~5.4 Go en fp16, tient sur Colab T4.

Usage :
    python 03_src/features/extract_blip2.py --batch 4
"""

from __future__ import annotations

import argparse
import logging
from pathlib import Path

import pandas as pd
import torch
from PIL import Image
from tqdm import tqdm
from transformers import Blip2ForConditionalGeneration, Blip2Processor

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

MODEL_ID = "Salesforce/blip2-opt-2.7b"

VQA_QUESTIONS = {
    "blip2_score_real": "Question: Is this a real photograph taken by a camera? Answer:",
    "blip2_score_ai": "Question: Is this image generated by an AI image generator? Answer:",
    "blip2_score_artifact": "Question: Are there visual artifacts or distortions in this image? Answer:",
}

CAPTION_PROMPT = "a photo of"


def load_blip2(device: str = None):
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"
    logger.info("Chargement BLIP-2 (device=%s)...", device)
    processor = Blip2Processor.from_pretrained(MODEL_ID)
    model = Blip2ForConditionalGeneration.from_pretrained(
        MODEL_ID,
        torch_dtype=torch.float16 if device == "cuda" else torch.float32,
    )
    model = model.to(device).eval()
    return model, processor, device


@torch.no_grad()
def caption_one(model, processor, image: Image.Image, device: str) -> str:
    inputs = processor(images=image, text=CAPTION_PROMPT, return_tensors="pt").to(device)
    if device == "cuda":
        inputs = {k: v.to(torch.float16) if v.dtype == torch.float32 else v for k, v in inputs.items()}
    out = model.generate(**inputs, max_new_tokens=30)
    text = processor.tokenizer.decode(out[0], skip_special_tokens=True).strip()
    return text


@torch.no_grad()
def vqa_yes_proba(model, processor, image: Image.Image, question: str, device: str) -> float:
    """Renvoie la probabilite que la reponse soit 'yes' a une question oui/non."""
    inputs = processor(images=image, text=question, return_tensors="pt").to(device)
    if device == "cuda":
        inputs = {k: v.to(torch.float16) if v.dtype == torch.float32 else v for k, v in inputs.items()}
    out = model.generate(
        **inputs, max_new_tokens=4, output_scores=True, return_dict_in_generate=True
    )
    text = processor.tokenizer.decode(out.sequences[0], skip_special_tokens=True).lower()
    answer = text.split("answer:")[-1].strip()
    # Heuristique : 1 si "yes", 0 si "no", 0.5 sinon
    if answer.startswith("yes"):
        return 1.0
    if answer.startswith("no"):
        return 0.0
    return 0.5


def extract_for_dataset(df: pd.DataFrame, root: Path, batch_size: int = 1) -> pd.DataFrame:
    model, processor, device = load_blip2()

    results = {k: [] for k in ["blip2_caption"] + list(VQA_QUESTIONS.keys())}

    for _, row in tqdm(df.iterrows(), total=len(df), desc="BLIP-2"):
        path = root / row["image_path"]
        try:
            img = Image.open(path).convert("RGB")
            cap = caption_one(model, processor, img, device)
            results["blip2_caption"].append(cap)
            for key, q in VQA_QUESTIONS.items():
                results[key].append(vqa_yes_proba(model, processor, img, q, device))
        except Exception as e:
            logger.warning("Echec %s : %s", path, e)
            results["blip2_caption"].append(None)
            for key in VQA_QUESTIONS:
                results[key].append(None)

    out = df.copy()
    for k, v in results.items():
        out[k] = v
    return out


def main():
    parser = argparse.ArgumentParser(description="Features BLIP-2")
    parser.add_argument("--dataset", type=Path,
                        default=Path("01_data/processed/dataset_with_clip.parquet"))
    parser.add_argument("--out", type=Path,
                        default=Path("01_data/processed/dataset_with_blip2.parquet"))
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--limit-to-domain", action="store_true",
                        help="Ne calcule que sur les splits domain_* (plus rapide pour les tests)")
    args = parser.parse_args()

    df = pd.read_parquet(args.dataset)
    if args.limit_to_domain:
        df = df[df["split"].astype(str).str.startswith("domain_")].reset_index(drop=True)
        logger.info("Limite au domaine habitation : %d lignes", len(df))

    out = extract_for_dataset(df, root=args.root)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    out.to_parquet(args.out, index=False)
    logger.info("Sauvegarde : %s", args.out)


if __name__ == "__main__":
    main()
