"""
Extraction de features image avec LLaVA-1.5-7B (4-bit).

Pour chaque image on demande a LLaVA un JSON structure :
  - llava_score_real        : score entre 0 et 1, plus eleve = plus reelle
  - llava_score_artifact    : presence d'artefacts visuels typiques d'IA
  - llava_score_coherence   : coherence interne de la scene (textures, ombres, perspectives)
  - llava_observation       : description courte des elements suspects ou rassurants

LLaVA-1.5-7B en 4-bit : ~5 Go VRAM, OK Colab T4.

Usage :
    python 03_src/features/extract_llava.py
"""

from __future__ import annotations

import argparse
import json
import logging
import re
from pathlib import Path

import pandas as pd
import torch
from PIL import Image
from tqdm import tqdm
from transformers import (
    AutoProcessor,
    BitsAndBytesConfig,
    LlavaForConditionalGeneration,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

MODEL_ID = "llava-hf/llava-1.5-7b-hf"

ANALYSIS_PROMPT = """USER: <image>
You are a forensic image analyst evaluating whether this picture is an AUTHENTIC photograph
or an image GENERATED BY AN AI MODEL (such as Stable Diffusion, Midjourney, DALL-E).

Look carefully for:
- Inconsistent textures, blurry boundaries between objects
- Impossible lighting / reflections / shadows
- Misaligned details (text, hands, repeated patterns)
- Over-smooth surfaces, unnatural colors

Reply ONLY with a JSON object (no commentary), with this exact schema:
{
  "score_real": float between 0 and 1 (probability the image is a real photograph),
  "score_artifact": float between 0 and 1 (presence of AI-generation artifacts),
  "score_coherence": float between 0 and 1 (internal scene coherence: shadows, perspective, textures),
  "observation": short string (max 200 chars), the most salient suspicious or reassuring detail
}
ASSISTANT:"""


def load_llava(device: str = None):
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"

    logger.info("Chargement LLaVA-1.5-7B (device=%s)...", device)
    processor = AutoProcessor.from_pretrained(MODEL_ID)

    if device == "cuda":
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_quant_type="nf4",
        )
        model = LlavaForConditionalGeneration.from_pretrained(
            MODEL_ID,
            quantization_config=bnb_config,
            device_map="auto",
        )
    else:
        model = LlavaForConditionalGeneration.from_pretrained(
            MODEL_ID, torch_dtype=torch.float32
        ).to(device)

    model.eval()
    return model, processor, device


@torch.no_grad()
def analyse_one(model, processor, image: Image.Image) -> dict:
    inputs = processor(text=ANALYSIS_PROMPT, images=image, return_tensors="pt").to(
        model.device, torch.float16 if model.device.type == "cuda" else torch.float32
    )
    outputs = model.generate(
        **inputs, max_new_tokens=200, do_sample=False, pad_token_id=processor.tokenizer.eos_token_id
    )
    text = processor.decode(outputs[0], skip_special_tokens=True)
    answer = text.split("ASSISTANT:")[-1].strip()
    return parse_json_answer(answer)


def parse_json_answer(text: str) -> dict:
    """Parse la reponse JSON de LLaVA, robuste aux ecarts mineurs."""
    default = {
        "llava_score_real": None,
        "llava_score_artifact": None,
        "llava_score_coherence": None,
        "llava_observation": None,
    }
    if not text:
        return default
    # On tente d'isoler le JSON
    match = re.search(r"\{[\s\S]*?\}", text)
    if not match:
        return default
    try:
        parsed = json.loads(match.group(0))
        return {
            "llava_score_real": _to_float(parsed.get("score_real")),
            "llava_score_artifact": _to_float(parsed.get("score_artifact")),
            "llava_score_coherence": _to_float(parsed.get("score_coherence")),
            "llava_observation": _to_str(parsed.get("observation")),
        }
    except (json.JSONDecodeError, TypeError):
        return default


def _to_float(v):
    if v is None:
        return None
    try:
        return max(0.0, min(1.0, float(v)))
    except (TypeError, ValueError):
        return None


def _to_str(v):
    if v is None:
        return None
    s = str(v).strip()
    return s[:300] if s else None


def extract_for_dataset(df: pd.DataFrame, root: Path) -> pd.DataFrame:
    model, processor, _ = load_llava()
    rows = []
    for _, row in tqdm(df.iterrows(), total=len(df), desc="LLaVA"):
        path = root / row["image_path"]
        try:
            img = Image.open(path).convert("RGB")
            res = analyse_one(model, processor, img)
        except Exception as e:
            logger.warning("Echec %s : %s", path, e)
            res = {
                "llava_score_real": None,
                "llava_score_artifact": None,
                "llava_score_coherence": None,
                "llava_observation": None,
            }
        rows.append(res)

    extra = pd.DataFrame(rows)
    return pd.concat([df.reset_index(drop=True), extra], axis=1)


def main():
    parser = argparse.ArgumentParser(description="Features LLaVA")
    parser.add_argument("--dataset", type=Path,
                        default=Path("01_data/processed/dataset_with_blip2.parquet"))
    parser.add_argument("--out", type=Path,
                        default=Path("01_data/processed/dataset_with_lmm.parquet"))
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--limit-to-domain", action="store_true")
    args = parser.parse_args()

    df = pd.read_parquet(args.dataset)
    if args.limit_to_domain:
        df = df[df["split"].astype(str).str.startswith("domain_")].reset_index(drop=True)
        logger.info("Limite au domaine habitation : %d lignes", len(df))

    out = extract_for_dataset(df, root=args.root)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    out.to_parquet(args.out, index=False)
    logger.info("Sauvegarde : %s", args.out)


if __name__ == "__main__":
    main()
