"""
Wrapper d'inference unifie pour la detection de fraude image + texte.

Utilisation typique (depuis l'app Streamlit) :

    from inference import FraudDetector
    detector = FraudDetector(model_dir="04_models", variant="lite")
    result = detector.predict(image=pil_img, claim_form={
        "claim_type": "water",
        "claim_date": "2026-04-15",
        "discovery_date": "2026-04-16",
        "circumstances": "...",
        ...
    })

Le wrapper detecte automatiquement quels modeles sont disponibles :
- CLIP : indispensable
- BLIP-2 / LLaVA : optionnels (mode degrade si absents)
- spaCy + Mistral : optionnels pour le LLM-judge

Les seuils de decision sont charges depuis 04_models/thresholds_*.json si presents,
sinon valeurs par defaut 0.3 / 0.7. Voir calibration.py pour la generation.
"""

from __future__ import annotations

import json
import logging
import re
from datetime import date, datetime
from pathlib import Path
from typing import Any

import joblib
import numpy as np

logger = logging.getLogger(__name__)


# =============================================================================
# Helpers : extraction des features image
# =============================================================================

def _safe_import(name: str):
    try:
        return __import__(name)
    except ImportError:
        return None


def extract_exif_features(image) -> dict:
    """Renvoie un dict de flags EXIF (toujours present, valeurs 0/1)."""
    from PIL import ExifTags
    info = {"exif_present": 0.0, "has_gps": 0.0}
    try:
        exif = image.getexif()
        if exif:
            info["exif_present"] = 1.0
            gps_tag_id = next((k for k, v in ExifTags.TAGS.items() if v == "GPSInfo"), None)
            if gps_tag_id is not None and gps_tag_id in exif:
                info["has_gps"] = 1.0
    except Exception:
        pass
    return info


# =============================================================================
# Prompts/questions repliques de extract_blip2.py et extract_llava.py
# =============================================================================

BLIP2_VQA_QUESTIONS = {
    "blip2_score_real": "Question: Is this a real photograph taken by a camera? Answer:",
    "blip2_score_ai": "Question: Is this image generated by an AI image generator? Answer:",
    "blip2_score_artifact": "Question: Are there visual artifacts or distortions in this image? Answer:",
}
BLIP2_CAPTION_PROMPT = "a photo of"

LLAVA_PROMPT = """USER: <image>
You are a forensic image analyst evaluating whether this picture is an AUTHENTIC photograph
or an image GENERATED BY AN AI MODEL (such as Stable Diffusion, Midjourney, DALL-E).

Look carefully for:
- Inconsistent textures, blurry boundaries between objects
- Impossible lighting / reflections / shadows
- Misaligned details (text, hands, repeated patterns)
- Over-smooth surfaces, unnatural colors

Reply ONLY with a JSON object (no commentary), with this exact schema:
{
  "score_real": float between 0 and 1 (probability the image is a real photograph),
  "score_artifact": float between 0 and 1 (presence of AI-generation artifacts),
  "score_coherence": float between 0 and 1 (internal scene coherence: shadows, perspective, textures),
  "observation": short string (max 200 chars), the most salient suspicious or reassuring detail
}
ASSISTANT:"""


def _parse_llava_json(text: str) -> dict:
    default = {
        "llava_score_real": 0.5,
        "llava_score_artifact": 0.5,
        "llava_score_coherence": 0.5,
    }
    if not text:
        return default
    match = re.search(r"\{[\s\S]*?\}", text)
    if not match:
        return default
    try:
        parsed = json.loads(match.group(0))

        def _clamp(v):
            try:
                return max(0.0, min(1.0, float(v)))
            except (TypeError, ValueError):
                return 0.5

        return {
            "llava_score_real": _clamp(parsed.get("score_real")),
            "llava_score_artifact": _clamp(parsed.get("score_artifact")),
            "llava_score_coherence": _clamp(parsed.get("score_coherence")),
        }
    except (json.JSONDecodeError, TypeError):
        return default


# =============================================================================
# FraudDetector
# =============================================================================

class FraudDetector:
    """Detecteur de fraude unifie. Charge ce qui est disponible dans model_dir."""

    DEFAULT_THRESHOLDS = {"low": 0.3, "mid": 0.5, "high": 0.7}

    def __init__(self, model_dir: str | Path = "04_models", variant: str = "lite",
                 device: str | None = None, load_lmm: bool = False, load_judge: bool = False):
        """
        Args:
            model_dir : repertoire contenant les .joblib et thresholds_*.json.
            variant : 'lite' ou 'full'.
            device : 'cuda' / 'cpu' / None (auto).
            load_lmm : si True, tente de charger BLIP-2 et LLaVA pour scorer les images.
                       A activer uniquement si vous avez du GPU. Sur HF Spaces gratuit, garder False.
            load_judge : si True, tente de charger Mistral pour le LLM-as-judge.
        """
        self.model_dir = Path(model_dir)
        self.variant = variant
        self.load_lmm_flag = load_lmm
        self.load_judge_flag = load_judge

        # Lazy-loaded components
        self._clip_model = None
        self._clip_preprocess = None
        self._blip2 = None
        self._blip2_proc = None
        self._llava = None
        self._llava_proc = None
        self._judge_model = None
        self._judge_tokenizer = None
        self._spacy_nlp = None

        # Device
        torch = _safe_import("torch")
        if device is None:
            device = "cuda" if (torch and torch.cuda.is_available()) else "cpu"
        self.device = device
        self.torch = torch

        # Classifieurs
        self.image_model_pkg = self._load_or_warn(
            self.model_dir / f"image_model_{variant}.joblib", "image_model"
        )
        self.multimodal_model_pkg = self._load_or_warn(
            self.model_dir / f"multimodal_model_{variant}.joblib", "multimodal_model"
        )

        # Seuils calibres (fallback aux defauts si fichier absent)
        self.image_thresholds = self._load_thresholds(
            self.model_dir / f"thresholds_image_{variant}.json"
        )
        self.multimodal_thresholds = self._load_thresholds(
            self.model_dir / f"thresholds_multimodal_{variant}.json"
        )

    def _load_or_warn(self, path: Path, label: str):
        if not path.exists():
            logger.warning("%s absent : %s -- mode degrade", label, path)
            return None
        try:
            return joblib.load(path)
        except Exception as e:
            logger.error("Echec chargement %s : %s", path, e)
            return None

    def _load_thresholds(self, path: Path) -> dict:
        if not path.exists():
            logger.info("Pas de seuils calibres a %s, fallback sur defauts", path)
            return dict(self.DEFAULT_THRESHOLDS)
        try:
            with path.open("r", encoding="utf-8") as f:
                data = json.load(f)
            return {
                "low": float(data.get("low", 0.3)),
                "mid": float(data.get("mid", 0.5)),
                "high": float(data.get("high", 0.7)),
            }
        except Exception as e:
            logger.warning("Echec lecture %s : %s", path, e)
            return dict(self.DEFAULT_THRESHOLDS)

    def is_ready(self) -> bool:
        """True si au moins le modele image est charge."""
        return self.image_model_pkg is not None

    # =========================================================================
    # CLIP (indispensable)
    # =========================================================================

    def _ensure_clip(self):
        if self._clip_model is not None:
            return
        import open_clip
        logger.info("Chargement CLIP ViT-L/14 sur %s...", self.device)
        model, _, preprocess = open_clip.create_model_and_transforms("ViT-L-14", pretrained="openai")
        self._clip_model = model.to(self.device).eval()
        self._clip_preprocess = preprocess

    def encode_image_clip(self, image) -> np.ndarray:
        """Renvoie l'embedding CLIP normalise L2 (768-d)."""
        self._ensure_clip()
        torch = self.torch
        with torch.no_grad():
            x = self._clip_preprocess(image).unsqueeze(0).to(self.device)
            f = self._clip_model.encode_image(x)
            f = f / f.norm(dim=-1, keepdim=True)
        return f.cpu().numpy().squeeze(0).astype(np.float32)

    # =========================================================================
    # LMM (optionnels) : BLIP-2 et LLaVA
    # =========================================================================

    def _ensure_blip2(self):
        if self._blip2 is not None or not self.load_lmm_flag:
            return
        try:
            from transformers import Blip2ForConditionalGeneration, Blip2Processor
            logger.info("Chargement BLIP-2 OPT-2.7B...")
            self._blip2_proc = Blip2Processor.from_pretrained("Salesforce/blip2-opt-2.7b")
            dtype = self.torch.float16 if self.device == "cuda" else self.torch.float32
            self._blip2 = Blip2ForConditionalGeneration.from_pretrained(
                "Salesforce/blip2-opt-2.7b", torch_dtype=dtype,
            ).to(self.device).eval()
        except Exception as e:
            logger.warning("Echec chargement BLIP-2 : %s -- mode degrade", e)
            self.load_lmm_flag = False

    def _ensure_llava(self):
        if self._llava is not None or not self.load_lmm_flag:
            return

        # Sur GPU contraint (ex : Colab L4 24 Go), LLaVA pose deux problemes :
        #   1) son inference echoue souvent (dtype mismatch fp16/fp32 avec bitsandbytes)
        #   2) sa presence en VRAM empeche Mistral fp16 de tenir entierement, ce qui
        #      provoque un CPU offload et rend l'inference 30-50x plus lente.
        # On le desactive donc volontairement sur cuda. BLIP-2 (fp16, leger) fournit
        # deja 3 scores VQA forensiques. Les scores llava_* restent a 0,5 (defaut).
        if self.device == "cuda":
            logger.info("LLaVA volontairement desactive sur GPU pour cohabiter avec BLIP-2 + Mistral fp16.")
            self._llava = None
            return

        try:
            from transformers import AutoProcessor, LlavaForConditionalGeneration
            logger.info("Chargement LLaVA-1.5-7B...")
            self._llava_proc = AutoProcessor.from_pretrained("llava-hf/llava-1.5-7b-hf")
            self._llava = LlavaForConditionalGeneration.from_pretrained(
                "llava-hf/llava-1.5-7b-hf", torch_dtype=self.torch.float32,
            ).eval()
        except Exception as e:
            logger.warning("Echec chargement LLaVA : %s -- mode degrade", e)
            self._llava = None

    @staticmethod
    def _vqa_yes_proba_blip2(model, processor, image, question: str, device: str, torch) -> float:
        with torch.no_grad():
            inputs = processor(images=image, text=question, return_tensors="pt").to(device)
            if device == "cuda":
                inputs = {k: v.to(torch.float16) if v.dtype == torch.float32 else v
                          for k, v in inputs.items()}
            out = model.generate(**inputs, max_new_tokens=4,
                                 output_scores=True, return_dict_in_generate=True)
            text = processor.tokenizer.decode(out.sequences[0], skip_special_tokens=True).lower()
        ans = text.split("answer:")[-1].strip()
        if ans.startswith("yes"):
            return 1.0
        if ans.startswith("no"):
            return 0.0
        return 0.5

    def lmm_features_image(self, image) -> dict:
        """Calcule les scores BLIP-2 et LLaVA pour une image au runtime.

        Si load_lmm=False (mode lite, CPU) : renvoie 0.5 partout (neutre).
        Sinon, charge les modeles a la volee et calcule les VRAIS scores.
        """
        out = {
            "blip2_score_real": 0.5, "blip2_score_ai": 0.5, "blip2_score_artifact": 0.5,
            "llava_score_real": 0.5, "llava_score_artifact": 0.5, "llava_score_coherence": 0.5,
        }
        if not self.load_lmm_flag:
            return out

        # ---- BLIP-2 ----
        self._ensure_blip2()
        if self._blip2 is not None:
            try:
                for key, q in BLIP2_VQA_QUESTIONS.items():
                    out[key] = self._vqa_yes_proba_blip2(
                        self._blip2, self._blip2_proc, image, q, self.device, self.torch
                    )
            except Exception as e:
                logger.warning("BLIP-2 VQA a echoue : %s", e)

        # ---- LLaVA ----
        self._ensure_llava()
        if self._llava is not None:
            try:
                with self.torch.no_grad():
                    inputs = self._llava_proc(text=LLAVA_PROMPT, images=image, return_tensors="pt").to(
                        self._llava.device,
                        self.torch.float16 if self._llava.device.type == "cuda" else self.torch.float32,
                    )
                    outputs = self._llava.generate(
                        **inputs, max_new_tokens=200, do_sample=False,
                        pad_token_id=self._llava_proc.tokenizer.eos_token_id,
                    )
                    text = self._llava_proc.decode(outputs[0], skip_special_tokens=True)
                answer = text.split("ASSISTANT:")[-1].strip()
                parsed = _parse_llava_json(answer)
                out.update(parsed)
            except Exception as e:
                logger.warning("LLaVA a echoue : %s", e)

        return out


    # =========================================================================
    # Texte
    # =========================================================================

    def _ensure_spacy(self):
        if self._spacy_nlp is not None:
            return
        try:
            import spacy
            self._spacy_nlp = spacy.load("fr_core_news_md")
        except Exception as e:
            logger.warning("spaCy fr_core_news_md indisponible : %s", e)
            self._spacy_nlp = False

    def extract_text_handcrafted(self, text: str) -> dict:
        if not text:
            return {k: 0 for k in [
                "txt_n_chars", "txt_n_words", "txt_n_sentences", "txt_ttr",
                "txt_n_dates", "txt_n_money", "txt_n_loc", "txt_n_persons", "txt_n_emphatic",
            ]}
        words = re.findall(r"\b\w+\b", text.lower())
        n_chars = len(text)
        n_words = len(words)
        n_sentences = max(1, len(re.findall(r"[.!?]+", text)))
        ttr = len(set(words)) / n_words if n_words > 0 else 0.0
        emphatic_set = {
            "totalement", "completement", "absolument", "entierement", "integralement",
            "catastrophe", "desastre", "drame", "horrible", "terrible",
            "tout est detruit", "rien n'a ete epargne", "absolument tout", "inestimable",
        }
        n_emphatic = sum(1 for kw in emphatic_set if kw in text.lower())

        n_dates = n_money = n_loc = n_persons = 0
        self._ensure_spacy()
        if self._spacy_nlp:
            try:
                doc = self._spacy_nlp(text)
                for ent in doc.ents:
                    if ent.label_ == "DATE":
                        n_dates += 1
                    elif ent.label_ == "MONEY":
                        n_money += 1
                    elif ent.label_ in ("LOC", "GPE"):
                        n_loc += 1
                    elif ent.label_ in ("PER", "PERSON"):
                        n_persons += 1
            except Exception:
                pass

        return {
            "txt_n_chars": n_chars, "txt_n_words": n_words, "txt_n_sentences": n_sentences,
            "txt_ttr": ttr,
            "txt_n_dates": n_dates, "txt_n_money": n_money,
            "txt_n_loc": n_loc, "txt_n_persons": n_persons,
            "txt_n_emphatic": n_emphatic,
        }

    def text_features_judge(self, text: str) -> dict:
        """LLM-as-judge sur le texte. Renvoie 5 scores entre 0 et 1.
        Si Mistral n'est pas charge, renvoie des 0.5 neutres."""
        out = {
            "judge_specificity": 0.5, "judge_coherence": 0.5,
            "judge_plausibility": 0.5, "judge_red_flags": 0.5,
            "judge_overall_genuine": 0.5,
        }
        if not self.load_judge_flag:
            return out
        try:
            from features.extract_text import judge_text, load_judge
            if self._judge_model is None:
                self._judge_model, self._judge_tokenizer = load_judge(device=self.device)
            res = judge_text(self._judge_model, self._judge_tokenizer, text)
            return {k: (v if v is not None else 0.5) for k, v in res.items()}
        except Exception as e:
            logger.warning("Judge a echoue : %s", e)
            return out

    # =========================================================================
    # Coherence inter-champs
    # =========================================================================

    @staticmethod
    def cross_field_coherence(form: dict[str, Any]) -> dict:
        """Calcule des features de coherence sur le formulaire structure."""
        coh = {
            "cf_delay_days": 0.0,
            "cf_amount_per_m2": 0.0,
            "cf_has_third_party": 0.0,
            "cf_has_witness": 0.0,
            "cf_authorities_called": 0.0,
            "cf_circumstances_short": 0.0,
        }
        try:
            cd = _to_date(form.get("claim_date"))
            dd = _to_date(form.get("discovery_date"))
            if cd and dd:
                coh["cf_delay_days"] = (dd - cd).days
        except Exception:
            pass
        amount = float(form.get("amount") or 0)
        surface = float(form.get("surface") or 0)
        if surface > 0:
            coh["cf_amount_per_m2"] = amount / surface
        coh["cf_has_third_party"] = 1.0 if form.get("third_party") else 0.0
        coh["cf_has_witness"] = 1.0 if form.get("witness") else 0.0
        coh["cf_authorities_called"] = 1.0 if form.get("authorities") else 0.0
        circ = form.get("circumstances") or ""
        coh["cf_circumstances_short"] = 1.0 if len(circ) < 80 else 0.0
        return coh

    # =========================================================================
    # Score image seul (utilise par occlusion)
    # =========================================================================

    def score_image_only(self, image, _skip_lmm: bool = True) -> float:
        """Renvoie uniquement le score image."""
        if self.image_model_pkg is None:
            raise RuntimeError("Aucun modele image charge.")
        clip_emb = self.encode_image_clip(image)
        exif = extract_exif_features(image)
        if _skip_lmm:
            lmm_feats = {
                "blip2_score_real": 0.5, "blip2_score_ai": 0.5, "blip2_score_artifact": 0.5,
                "llava_score_real": 0.5, "llava_score_artifact": 0.5, "llava_score_coherence": 0.5,
            }
        else:
            lmm_feats = self.lmm_features_image(image)
        feat_names = self.image_model_pkg["feature_names"]
        n_clip = sum(1 for n in feat_names if n.startswith("clip_"))
        extras = [n for n in feat_names if not n.startswith("clip_")]
        feature_values = {**exif, **lmm_feats}
        extras_arr = np.array([float(feature_values.get(n, 0.5)) for n in extras], dtype=np.float32)
        X_img = np.concatenate([clip_emb[:n_clip], extras_arr]).reshape(1, -1)
        X_img_s = self.image_model_pkg["scaler"].transform(X_img)
        return float(self.image_model_pkg["model"].predict_proba(X_img_s)[0, 1])

    # =========================================================================
    # Explicabilite image
    # =========================================================================

    def explain_image(self, image, patch_size: int = 56, stride: int = 28) -> dict:
        """Calcule une heatmap d'occlusion sur l'image."""
        from utils.explain import occlusion_heatmap, overlay_heatmap
        scorer = lambda img: self.score_image_only(img, _skip_lmm=True)
        base_score = scorer(image)
        heatmap = occlusion_heatmap(image, scorer, patch_size=patch_size, stride=stride)
        overlay = overlay_heatmap(image, heatmap)
        return {"heatmap": heatmap, "overlay": overlay, "base_score": base_score}

    # =========================================================================
    # Decision
    # =========================================================================

    def _decide(self, score: float, thresholds: dict) -> tuple[str, str]:
        """Renvoie (decision, color) selon les seuils calibres."""
        low, high = thresholds.get("low", 0.3), thresholds.get("high", 0.7)
        if score < low:
            return "Légitime", "green"
        if score < high:
            return "À expertiser", "orange"
        return "Fraude probable", "red"

    # =========================================================================
    # Pipeline complet
    # =========================================================================

    def predict(self, image, claim_form: dict | None = None) -> dict:
        """Predict. Retourne un dict structure pour l'app Streamlit."""
        if self.image_model_pkg is None:
            raise RuntimeError(
                "Aucun modele image charge. Lance d'abord :\n"
                f"  python 03_src/models/train_image_model.py --variant {self.variant}"
            )

        # 1) Features image
        clip_emb = self.encode_image_clip(image)
        exif = extract_exif_features(image)
        lmm_feats = self.lmm_features_image(image)

        # 2) Reconstruire X_image en respectant feature_names du modele
        feat_names = self.image_model_pkg["feature_names"]
        n_clip = sum(1 for n in feat_names if n.startswith("clip_"))
        extras = [n for n in feat_names if not n.startswith("clip_")]
        feature_values = {**exif, **lmm_feats}
        extras_arr = np.array([float(feature_values.get(n, 0.5)) for n in extras], dtype=np.float32)
        X_img = np.concatenate([clip_emb[:n_clip], extras_arr]).reshape(1, -1)
        X_img_s = self.image_model_pkg["scaler"].transform(X_img)
        score_image = float(self.image_model_pkg["model"].predict_proba(X_img_s)[0, 1])

        # 3) Features texte si declaration fournie
        text_feats = {}
        score_multimodal = None
        if claim_form is not None:
            circ = claim_form.get("circumstances", "") or ""
            text_feats.update(self.extract_text_handcrafted(circ))
            text_feats.update(self.text_features_judge(circ))
            text_feats.update(self.cross_field_coherence(claim_form))

            if self.multimodal_model_pkg is not None:
                mm_names = self.multimodal_model_pkg["feature_names"]
                row = []
                missing = []
                for n in mm_names:
                    if n == "score_image":
                        row.append(score_image)
                    elif n in text_feats:
                        row.append(float(text_feats[n]))
                    else:
                        missing.append(n)
                        row.append(0.0)
                if missing:
                    logger.debug("Features multimodales absentes (impute 0.0) : %s", missing)
                X_mm = np.array(row, dtype=np.float32).reshape(1, -1)
                X_mm_s = self.multimodal_model_pkg["scaler"].transform(X_mm)
                score_multimodal = float(self.multimodal_model_pkg["model"].predict_proba(X_mm_s)[0, 1])

        # 4) Decision (avec seuils calibres si dispo)
        if score_multimodal is not None:
            score_used = score_multimodal
            thresholds_used = self.multimodal_thresholds
        else:
            score_used = score_image
            thresholds_used = self.image_thresholds
        decision, decision_color = self._decide(score_used, thresholds_used)

        return {
            "score_image": score_image,
            "score_multimodal": score_multimodal,
            "score_used": score_used,
            "decision": decision,
            "decision_color": decision_color,
            "thresholds_used": thresholds_used,
            "image_features": {**exif, **lmm_feats},
            "text_features": text_feats,
        }


# =============================================================================
# Helpers
# =============================================================================

def _to_date(v) -> date | None:
    if v is None:
        return None
    if isinstance(v, date):
        return v
    if isinstance(v, str):
        for fmt in ("%Y-%m-%d", "%d/%m/%Y", "%d-%m-%Y"):
            try:
                return datetime.strptime(v, fmt).date()
            except ValueError:
                continue
    return None
